"use client";
import {useEffect,useMemo,useState} from "react";
import {calibrationBuckets,gradeProjection,summarize,type ProjectionSnapshot} from "../lib/performance";
import {loadSnapshots} from "../lib/projectionStore";
export default function ModelPerformance(){
 const [rows,setRows]=useState<ProjectionSnapshot[]>([]);
 useEffect(()=>{const load=()=>setRows(loadSnapshots());load();window.addEventListener("storage",load);window.addEventListener("rounders:snapshot",load);return()=>{window.removeEventListener("storage",load);window.removeEventListener("rounders:snapshot",load)}},[]);
 const grades=useMemo(()=>rows.map(gradeProjection),[rows]),stats=useMemo(()=>summarize(grades),[grades]),cal=useMemo(()=>calibrationBuckets(grades),[grades]);
 const pct=(n:number|null)=>n===null?"Awaiting results":n.toFixed(1)+"%";
 return <section className="panel performance"><div><p className="tag">MODEL SCORECARD</p><h2>Rounders has to prove itself.</h2><p className="muted">Pregame projections are frozen before results are graded. ATS and CLV stay unavailable until real market snapshots exist.</p></div><div className="performanceGrid"><div className="metric"><small>Snapshots</small><strong>{rows.length}</strong><span>{stats.completed} completed</span></div><div className="metric"><small>Winner accuracy</small><strong>{pct(stats.winnerAccuracy)}</strong><span>straight-up</span></div><div className="metric"><small>Margin error</small><strong>{stats.meanAbsoluteMarginError===null?"Awaiting results":stats.meanAbsoluteMarginError.toFixed(2)}</strong><span>mean absolute error</span></div><div className="metric"><small>Brier score</small><strong>{stats.brierScore===null?"Awaiting results":stats.brierScore.toFixed(3)}</strong><span>lower is better</span></div><div className="metric"><small>ATS</small><strong>{stats.atsRecord.wins}-{stats.atsRecord.losses}-{stats.atsRecord.pushes}</strong><span>{pct(stats.atsWinRate)}</span></div><div className="metric"><small>Avg spread CLV</small><strong>{stats.averageClvPoints===null?"Awaiting close":stats.averageClvPoints.toFixed(2)}</strong><span>points</span></div></div>{cal.some(x=>x.predictions>0)&&<div className="calibration"><small>PROBABILITY CALIBRATION</small>{cal.filter(x=>x.predictions).map(x=><span key={x.range}>{x.range}: {x.actualWinRate?.toFixed(0)}% actual ({x.predictions})</span>)}</div>}</section>
}