name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
    
    - name: Run tests
      env:
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        SPORTSDATA_API_KEY: ${{ secrets.SPORTSDATA_API_KEY }}
        FOOTBALL_DATA_KEY: ${{ secrets.FOOTBALL_DATA_KEY }}
      run: |
        pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to Streamlit Cloud
      env:
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        SPORTSDATA_API_KEY: ${{ secrets.SPORTSDATA_API_KEY }}
        FOOTBALL_DATA_KEY: ${{ secrets.FOOTBALL_DATA_KEY }}
        STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}
      run: |
        # Install Streamlit CLI
        pip install streamlit-cli
        
        # Deploy to Streamlit Cloud
        streamlit deploy streamlit_app.py \
          --api-key $STREAMLIT_API_KEY \
          --branch main \
          --message "Automated deployment from GitHub Actions" 